USE [master]
GO
/*
/****** Object:  Database [dbOdev1]    Script Date: 9.05.2024 19:22:37 ******/
CREATE DATABASE [dbOdev1]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'dbOdev1', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\dbOdev1.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'dbOdev1_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\dbOdev1_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [dbOdev1].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [dbOdev1] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [dbOdev1] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [dbOdev1] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [dbOdev1] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [dbOdev1] SET ARITHABORT OFF 
GO

ALTER DATABASE [dbOdev1] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [dbOdev1] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [dbOdev1] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [dbOdev1] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [dbOdev1] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [dbOdev1] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [dbOdev1] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [dbOdev1] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [dbOdev1] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [dbOdev1] SET  DISABLE_BROKER 
GO

ALTER DATABASE [dbOdev1] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [dbOdev1] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [dbOdev1] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [dbOdev1] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [dbOdev1] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [dbOdev1] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [dbOdev1] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [dbOdev1] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [dbOdev1] SET  MULTI_USER 
GO

ALTER DATABASE [dbOdev1] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [dbOdev1] SET DB_CHAINING OFF 
GO

ALTER DATABASE [dbOdev1] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [dbOdev1] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [dbOdev1] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [dbOdev1] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [dbOdev1] SET QUERY_STORE = ON
GO

ALTER DATABASE [dbOdev1] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [dbOdev1] SET  READ_WRITE 
GO


USE [dbOdev1]
GO

/****** Object:  Table [dbo].[Categories]    Script Date: 9.05.2024 19:22:54 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO
*/
CREATE TABLE [dbo].[Categories](
	[CategoryID] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nchar](10) NULL,
 CONSTRAINT [PK_Categories] PRIMARY KEY CLUSTERED 
(
	[CategoryID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

USE [dbOdev1]
GO

/****** Object:  Table [dbo].[Products]    Script Date: 9.05.2024 19:23:06 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE TABLE [dbo].[Products](
	[ProductID] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](100) NOT NULL,
	[UnitPrice] [money] NULL,
	[UnitsInStock] [int] NULL,
	[CategoryID] [int] NULL,
 CONSTRAINT [PK_Products] PRIMARY KEY CLUSTERED 
(
	[ProductID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Products]  WITH CHECK ADD  CONSTRAINT [FK_Products_Categories] FOREIGN KEY([CategoryID])
REFERENCES [dbo].[Categories] ([CategoryID])
GO

ALTER TABLE [dbo].[Products] CHECK CONSTRAINT [FK_Products_Categories]
GO

