USE [DbUlke]
GO

/****** Object:  Table [dbo].[MAHALLEKOY]    Script Date: 7.05.2024 21:36:08 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[MAHALLEKOY](
	[KOD] [nchar](10) NOT NULL,
	[ADI] [nvarchar](50) NOT NULL,
	[ILCEKOD] [nchar](10) NOT NULL,
 CONSTRAINT [PK_MAHALLEKOY] PRIMARY KEY CLUSTERED 
(
	[KOD] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[MAHALLEKOY]  WITH CHECK ADD  CONSTRAINT [FK_MAHALLEKOY_ILCE] FOREIGN KEY([ILCEKOD])
REFERENCES [dbo].[ILCE] ([KOD])
GO

ALTER TABLE [dbo].[MAHALLEKOY] CHECK CONSTRAINT [FK_MAHALLEKOY_ILCE]
GO


