USE [DbUlke]
GO

/****** Object:  Table [dbo].[IL]    Script Date: 7.05.2024 21:35:21 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[IL](
	[KOD] [nchar](10) NOT NULL,
	[ADI] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_IL] PRIMARY KEY CLUSTERED 
(
	[KOD] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


