USE [DbUlke]
GO

/****** Object:  Table [dbo].[ILCE]    Script Date: 7.05.2024 21:35:46 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[ILCE](
	[KOD] [nchar](10) NOT NULL,
	[ADI] [nvarchar](50) NOT NULL,
	[ILKOD] [nchar](10) NOT NULL,
 CONSTRAINT [PK_ILCE] PRIMARY KEY CLUSTERED 
(
	[KOD] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[ILCE]  WITH CHECK ADD  CONSTRAINT [FK_ILCE_IL] FOREIGN KEY([ILKOD])
REFERENCES [dbo].[IL] ([KOD])
GO

ALTER TABLE [dbo].[ILCE] CHECK CONSTRAINT [FK_ILCE_IL]
GO


